---
- hosts: vm
  remote_user: ubuntu
  sudo: yes
  tasks:
   - name: update apt
     command: apt-get update

   - name: insall vim and curl
     apt: name={{item}} state=installed
     with_items:
       - vim
       - curl

   - name: download-couchdb
     get_url:
       url: https://raw.githubusercontent.com/afiskon/install-couchdb/master/install-couchdb.sh
       dest: /home/ubuntu

   - name: install couchdb
     command: sh install-couchdb.sh

   - name: Add Java repository to
     action: apt_repository repo='ppa:webupd8team/java'

   - name: Autoaccept license for Java
     shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

   - name: Update APT package cache
     apt: update_cache=yes

   - name: Install Java 8
     apt: pkg=oracle-java8-installer state=latest install_recommends=yes

   - name: Set Java 8 Env
     apt: pkg=oracle-java8-set-default state=latest install_recommends=yes

   - name: modify local.ini
     lineinfile:
      path: /home/couchdb/etc/local.ini
      insertafter: "{{ item.insertafter }}"
      line: "{{ item.line }}"
     with_items:
        - { insertafter: '\[chttpd]', line: 'bind_address = 0.0.0.0' }
        - { insertafter: '\[chttpd]', line: 'port = 5984' }
        - { insertafter: '\[httpd]', line: 'replace' }
        - { insertafter: '\[admin]', line: 'admin = password' }

   - name: modify local.ini, replace the content under [httpd]
     lineinfile:
      path: /home/couchdb/etc/local.ini
      regexp: 'replace'
      line: 'bind_address = 0.0.0.0'

   - name: modify vm.args
     lineinfile:
      path: /home/couchdb/etc/vm.args
      regexp: '-name couchdb@localhost'
      line: "-name couchdb@{{ inventory_hostname }}"

   - name: modify sys.config
     lineinfile:
      path: /home/couchdb/releases/2.0.0/sys.config
      regexp: '\[]\.'
      line: >
            [
              {lager, [
                  {error_logger_hwm, 1000},
                  {error_logger_redirect, true},
                  {handlers, [
                      {lager_console_backend, [debug, {
                          lager_default_formatter,
                          [
                              date, " ", time,
                              " [", severity, "] ",
                              node, " ", pid, " ",
                              message,
                              "\n"
                          ]
                      }]}
                  ]},
                  {inet_dist_listen_min, 9100},
                  {inet_dist_listen_max, 9200}
              ]}
            ].

   - name: enable cluster
     command: 'curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d "{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 5984}"'

   - name: restart couchdb
     command: sv restart couchdb

